product = "Angry Birds Space"
publisher = "Rovio"
name = "Angry Birds Space"
width = 1024
height = 600
orientation = 0
datapath = "data"
imagePath = "images"
fontPath = "fonts"
audioPath = "audio"
localizationPath = "localization"
levelPath = "levels"
scriptPath = "scripts"
commonScriptPath = "scripts_common"
shaderPath = "shaders"
deviceModel = "windows"
fullscreen = false
showCursor = false
singleton = true
renderer = { "gl1" }